name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: installopencv
      run: git clone https://github.com/opencv/opencv.git &&
           cd opencv &&
           mkdir build &&
           cd build &&
           cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local .. &&
           make -j7 &&
           sudo make install &&
           cd ../../
    - name: mkdirbuild
      run: mkdir build
    - name: cmake1
      run: cmake -Bbuild ./src
    - name: cmake2
      run: cmake --build build
    - name: test
      run: ./build/tests
