name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install dependencies from APT
      run: |
        sudo apt install curl wget
        sudo curl -s --compressed "https://huskyroboticsteam.github.io/ubuntu-repo/KEY.gpg" | sudo apt-key add -
        sudo wget -P /etc/apt/sources.list.d "https://huskyroboticsteam.github.io/ubuntu-repo/husky_robotics.list"
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y build-essential wget unzip curl gnupg2 lsb-release git \
          cmake libsfml-dev libeigen3-dev libopencv-dev libopencv-contrib-dev \
          libwebsocketpp-dev libboost-system-dev gpsd gpsd-clients libgps-dev nlohmann-json3-dev \
          catch2 urg-lidar rplidar ublox-linux hindsight-can frozen
    - name: Build codebase
      run: |
        cd ${{ github.workspace }}
        mkdir build && cd build && cmake ../src && cmake --build . -j$(nproc)
    - name: Run tests
      run: |
        ./build/tests
