name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: installopencv
      run: sudo apt-get install libopencv-core-dev
    - name: find
      run: find /usr/ -name "OpenCVConfig.cmake"
    - name: mkdirbuild
      run: mkdir build
    - name: cmake1
      run: cmake -Bbuild ./src
    - name: cmake2
      run: cmake --build build
    - name: test
      run: ./build/tests
