name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install dependencies from APT
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y build-essential wget unzip curl gnupg2 lsb-release git \
          cmake libsfml-dev libeigen3-dev libopencv-dev libopencv-contrib-dev \
          libwebsocketpp-dev libboost-system-dev gpsd gpsd-clients libgps-dev nlohmann-json3-dev
    - name: Build and install Catch2
      run: |
        git clone https://github.com/catchorg/catch2 /tmp/catch2
        cd /tmp/catch2 && git checkout v2.13.4
        mkdir build && cd build
        cmake .. -DBUILD_TESTING=OFF && sudo cmake --build . --target install
    - name: Build and install urg-lidar
      run: |
        git clone https://github.com/huskyroboticsteam/urg-lidar.git /tmp/urg-lidar
        cd /tmp/urg-lidar && mkdir build && cd build
        cmake .. && sudo cmake --build . --target install
    - name: Build codebase
      run: |
        cd ${{ github.workspace }}
        mkdir build && cd build && cmake ../src && cmake --build . -j$(nproc)
    - name: Run tests
      run: |
        ./build/tests
