name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: installopencv
      run: git clone https://github.com/opencv/opencv.git
      run: cd opencv
      run: mkdir build
      run: cd build
      run: cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
      run: make -j7
      run: cd ../../
    - name: mkdirbuild
      run: mkdir build
    - name: cmake1
      run: cmake -Bbuild ./src
    - name: cmake2
      run: cmake --build build
    - name: test
      run: ./build/tests
